openapi: 3.0.1
info:
  title: Products CRUD Operations Specifications
  description: Products CRUD Operations Specifications
  version: 1.0.0
  contact:
    email: eric.gitonga38@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'http://localhost:9000/v2'
    description: Local Development Server
  - url: "http://192.168.41.23:8080"
    description: Development Environment Server
  - url: "http://api.imbank.co.ke/v2"
    description: Production Server

# Specifying security for the whole project
#security:
#  -ApiKey: []

paths:
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: Create user functionality
      operationId: createUser
      requestBody:
        description: User object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestResponse'

  /user/{username}:
    get:
      tags:
        - user
      summary: Get user by user name
      # Specifying security for a specific path, uncomment below two lines
      #      security:
      #        - ApiKey: []
      operationId: getUserByName
      parameters:
        - name: username
          in: path
          description: 'The name that needs to be fetched'
          required: true
          schema:
            type: string
      responses:
        200:
          description: Succeessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: User not found
          content: {}
  /users:
    get:
      tags:
        - users
      summary: Get all the available users
      operationId: getAllUsers
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        404:
          description: Users not found
          content: {}

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        userStatus:
          type: integer
          description: User status
          format: int32
    RequestResponse:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
        message:
          type: string

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://192.168.205.135:2284/BackbaseOAuthToken/1.0/
          scopes:
            write: Grants write access
    ImplicitFlow:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://reflectoring.swagger.io/oauth/dialog
          scopes:
            write:users: modify users
            read:users: read users
    ApiKey:
      type: apiKey
      name: api_key
      in: header

  
